# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TQ02OeKo1imUdHyKc--HpnKAUw4KzeA
"""

int(2.3)

int(2.5)

"""type casting

"""

bool(2)

bool(3.2)

bool(0+0j)

bool("hi")

bool( )

str(3.4)

str(1+3j)

str(True)

"""Type casting is done

#Python Operator
-arithmetic operator(+,-,*,/,//,)
"""

x1, y1 = 15,5

x1+y1

x1 - y1

x1/y1

x1//y1

x1**y1

x1*y1

"""#Assignment operator"""

x = 2
x

x = x + 2
x

x += 2
x

x += 5
x

from os import XATTR_SIZE_MAX
x =+ 2
XATTR_SIZE_MAX

x -= 5
x

x *= 2
x

x /= 2
x

x //= 2
x

x // 2
2



"""#Unary operator

"""

n = 7 #negattion
n

m = -(n)
m

m

"""#relational operators"""

r1 = 5
r2 = 6

r1>r2

r1<r2

r1<=r2

r1>=r2

r1==r2

r1!=r2

r=7

r3 = 7

r1>=r3

r1<r3



"""#Logical Operators
AND operator
1 and 1 = 1
1 and 0 = 0
0 and 0 = 0
0 and 1 = 0

OR operator
0 or 0 = 0
0 or 1 = 1
1 or 0 = 1
1 or 1 = 1

NOT operator
1 not 1 = 0
1 not 0 = 1
o not 1 = 1
0 not 0 = 1
"""

a = 5
b = 10

a < 8 and b < 5

a < 8 and b < 12

a > 4 and b > 13

a > 4 and b > 8

a < 8 or b < 12

a > 6 or b > 8

a > 7 or b > 12

a > 6 and b > 8

a > 4 and b > 8







